development:
  host: localhost
  database: bbp_health_development
  
test:
  host: localhost
  database: bbp_health_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>

