development:
  url: 'http://localhost:9200'
test:
  url: 'http://localhost:9200'
# set these environment variables on your prod server
production:
  url: "http://index.bonsai.io/g35gaprwbstqvzjthuot"
